# Generated by Django 4.2.3 on 2023-07-04 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_demo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Demo',
        ),
    ]
