# Generated by Django 4.2.3 on 2023-07-04 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_delete_demo'),
    ]

    operations = [
        migrations.AddField(
            model_name='screenshot',
            name='IP',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
