# Generated by Django 4.2.3 on 2023-07-04 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_screenshot_ip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='screenshot',
            name='IP',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
