# Generated by Django 4.2.3 on 2023-07-05 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_screenshot_ip'),
    ]

    operations = [
        migrations.AddField(
            model_name='screenshot',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='screenshot',
            name='username',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
    ]
