# Generated by Django 4.2.3 on 2023-07-05 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_screenshot_created_at_screenshot_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='screenshot',
            name='username',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
