# Generated by Django 4.2.3 on 2023-07-05 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_alter_screenshot_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, default='none', max_length=100, null=True, unique=True)),
                ('IP', models.CharField(max_length=70)),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('ss_count', models.IntegerField(blank=True, default=3, null=True)),
                ('time_gap', models.IntegerField(blank=True, default=10, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='screenshot',
            name='username',
        ),
    ]
