# Generated by Django 4.2.3 on 2023-07-11 05:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_alter_user_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='screenshot',
            old_name='IP',
            new_name='host',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='IP',
            new_name='host',
        ),
        migrations.AlterField(
            model_name='user',
            name='end_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 7, 11, 6, 30), null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='start_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 7, 11, 9, 0), null=True),
        ),
    ]
