# Generated by Django 4.2.3 on 2023-07-26 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_rename_ip_screenshot_host_rename_ip_user_host_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='screenshot',
            name='screen_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='time_gap',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
